baseURL = 'https://bobbyxdevel-gh.github.io/'
languageCode = 'en-us'
title = 'bobbyx.de'
theme = 'PaperMod'

[params]
defaultTheme = "auto" # auto, light, dark

[params.profileMode]
enabled = true
title = "bobbyx.de" # Shown under image
subtitle = "Showcasing dotfiles, docs, and thoughts."

[[params.profileMode.buttons]]
name = "Dotfiles"
url = "/dotfiles"

[[params.profileMode.buttons]]
name = "Docs"
url = "/docs"

[[params.profileMode.buttons]]
name = "Blog"
url = "/blog"

[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.socialIcons]] # Optional
name = "github"
url = "https://github.com/bobbyxdevel-gh/" # Replace with your GitHub username for the profile link

[menu]
[[menu.main]]
identifier = "dotfiles"
name = "Dotfiles"
url = "/dotfiles/"
weight = 10
[[menu.main]]
identifier = "docs"
name = "Docs"
url = "/docs/"
weight = 20
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 30
[[menu.main]]
identifier = "about-me"
name = "About"
url = "/about/"
weight = 40
